### ISSUE TITLE
Make an option to either use REV's Control Hub's built in IMU or deadwheels

### ISSUE THREAD

**Issue by itschesterlk** [itschesterlk/TweetyBird#9]

**Comment by TeameurekaRobotics** [comment]
or better yet, have them monitor each other as a redundant check. This way, if one fails, the other will provide needed information.

**Comment by itschesterlk** [comment]
> or better yet, have them monitor each other as a redundant check. This way, if one fails, the other will provide needed information.

That shall be the third option.

**Comment by itschesterlk** [comment]
Not necessary at the moment, deadwheels suffice.
